[build]
  command = "node build.js"
  publish = "dist"

[build.environment]
  # Environment variables will be set in Netlify dashboard
  NODE_VERSION = "18"
  # Allow client-side API keys in build output
  # Firebase and Google Maps keys are meant to be public in client-side code
  SECRETS_SCAN_OMIT_PATHS = "dist/index.html,dist/script.js"